# Generated by Django 4.2.7 on 2024-05-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderTracker',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=225)),
                ('purchase_order_number', models.CharField(max_length=225)),
                ('amount', models.FloatField(max_length=5)),
                ('purchase_order_id', models.CharField(max_length=225)),
                ('category_id', models.CharField(choices=[('A', 'Cat A'), ('B', 'Cat B'), ('C', 'Cat C'), ('D', 'Cat D')], default='A', max_length=1)),
            ],
        ),
    ]
